---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment-loadbalancer
 labels:
  app: myapp-app-loadbalancer
spec:
 replicas: 1
 selector:
  matchLabels:
   app: myapp-app-loadbalancer
 template:
  metadata: 
   labels:
    app: myapp-app-loadbalancer
  spec:
   containers:
   - name: myapp-app-loadbalancer
     image: gcr.io/jenkins-407204/demo@sha256:15e99b44fc3991347e58029ae070397f6c9ac9ee6316484a6e4b595ace200ff5
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: myapp-app-loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
